# app_urls.py

app_urls = {
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "github": "https://www.github.com",
    "linkedin": "https://www.linkedin.com",
    "twitter": "https://www.twitter.com",
    "facebook": "https://www.facebook.com",
    "instagram": "https://www.instagram.com",
    "reddit": "https://www.reddit.com",
    "amazon": "https://www.amazon.com",
    "netflix": "https://www.netflix.com",
    "stackoverflow": "https://stackoverflow.com",
    "wikipedia": "https://www.wikipedia.org",
    "microsoft": "https://www.microsoft.com",
    "apple": "https://www.apple.com",
    "bing": "https://www.bing.com",
    "yahoo": "https://www.yahoo.com",
    "quora": "https://www.quora.com",
    "medium": "https://www.medium.com",
    "spotify": "https://www.spotify.com",
    "dropbox": "https://www.dropbox.com",
    "zoom": "https://www.zoom.us",
    "slack": "https://www.slack.com",
    "trello": "https://www.trello.com",
    "figma": "https://www.figma.com",
    "dribbble": "https://www.dribbble.com",
    "behance": "https://www.behance.net",
}
